// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentSessionState() {
  return window['go']['main']['App']['GetCurrentSessionState']();
}

export function GetCurrentTime() {
  return window['go']['main']['App']['GetCurrentTime']();
}

export function GetNextSessionState() {
  return window['go']['main']['App']['GetNextSessionState']();
}

export function GetPomodoroSessionStates() {
  return window['go']['main']['App']['GetPomodoroSessionStates']();
}

export function GetPomodoroSettings() {
  return window['go']['main']['App']['GetPomodoroSettings']();
}

export function GetRemainingTime() {
  return window['go']['main']['App']['GetRemainingTime']();
}

export function PausePomodoro() {
  return window['go']['main']['App']['PausePomodoro']();
}

export function ResetPomodoro() {
  return window['go']['main']['App']['ResetPomodoro']();
}

export function ResumePomodoro() {
  return window['go']['main']['App']['ResumePomodoro']();
}

export function StartPomodoro() {
  return window['go']['main']['App']['StartPomodoro']();
}

export function UpdateSessionState() {
  return window['go']['main']['App']['UpdateSessionState']();
}
