// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {time} from '../models';

export function GetCurrentSessionState():Promise<models.SessionState>;

export function GetCurrentTime():Promise<time.Duration>;

export function GetNextSessionState():Promise<models.SessionState>;

export function GetPomodoroSessionStates():Promise<models.SessionState>;

export function GetPomodoroSettings():Promise<models.PomodoroSettings>;

export function GetRemainingTime():Promise<time.Duration>;

export function PausePomodoro():Promise<void>;

export function ResetPomodoro():Promise<void>;

export function ResumePomodoro():Promise<void>;

export function StartPomodoro():Promise<void>;

export function UpdateSessionState():Promise<void>;
